import type { Property, SiteSettings } from './types';

export function mapProperty(row: Record<string, unknown>): Property {
  const district = row.location as Record<string, unknown> | null;
  const cityLocation = district?.parent as Record<string, unknown> | null;
  const region = cityLocation?.parent as Record<string, unknown> | null;
  return {
    id:             row.id as string,
    propertyId:     row.property_id as string,
    slug:           row.slug as string,
    title:          row.title as string,
    titleUr:        row.title_ur as string | null,
    titleAr:        (row.title_ar ?? row.title_ur) as string | null,
    description:    row.description as string | null,
    descriptionUr:  row.description_ur as string | null,
    descriptionAr:  (row.description_ar ?? row.description_ur) as string | null,
    purpose:        row.purpose as Property['purpose'],
    category:       row.category as Property['category'],
    subCategory:    row.sub_category as string | null,
    status:         (row.status as Property['status']) ?? 'AVAILABLE',
    priceType:      (row.price_type as Property['priceType']) ?? 'FIXED',
    price:          row.price != null ? Number(row.price) : null,
    rentPrice:      row.rent_price != null ? Number(row.rent_price) : null,
    size:           Number(row.size),
    sizeUnit:       (row.size_unit as Property['sizeUnit']) ?? 'SQM',
    bedrooms:       row.bedrooms != null ? Number(row.bedrooms) : null,
    bathrooms:      row.bathrooms != null ? Number(row.bathrooms) : null,
    floors:         row.floors != null ? Number(row.floors) : null,
    facing:         row.facing as string | null,
    city:           (row.city as string) ?? 'Riyadh',
    society:        row.society as string | null,
    area:           row.area as string | null,
    address:        row.address as string | null,
    addressAr:      row.address_ar as string | null,
    locationId:     row.location_id as string | null,
    regionNameAr:   region?.name_ar as string | null,
    regionNameEn:   region?.name_en as string | null,
    cityNameAr:     cityLocation?.name_ar as string | null,
    cityNameEn:     cityLocation?.name_en as string | null,
    districtNameAr: district?.name_ar as string | null,
    districtNameEn: district?.name_en as string | null,
    mapLat:         row.map_lat as number | null,
    mapLng:         row.map_lng as number | null,
    photos:         (row.photos as string[]) ?? [],
    isCorner:       Boolean(row.is_corner),
    isParkFacing:   Boolean(row.is_park_facing),
    isGated:        Boolean(row.is_gated),
    hasSecurity:    Boolean(row.has_security),
    hasGas:         Boolean(row.has_gas),
    hasElectricity: Boolean(row.has_electricity),
    hasWater:       Boolean(row.has_water),
    hasGarage:      Boolean(row.has_garage),
    hasGarden:      Boolean(row.has_garden),
    hasServantQtr:  Boolean(row.has_servant_qtr),
    furnished:      (row.furnished as Property['furnished']) ?? 'UNFURNISHED',
    propertyAge:    row.property_age == null ? null : Number(row.property_age),
    amenities:      (row.amenities as string[]) ?? [],
    isDemo:         Boolean(row.is_demo),
    possession:     (row.possession as Property['possession']) ?? 'AVAILABLE',
    featured:       Boolean(row.featured),
    isActive:       Boolean(row.is_active),
    views:          Number(row.views ?? 0),
    createdAt:      row.created_at instanceof Date ? row.created_at.toISOString() : String(row.created_at ?? ''),
    updatedAt:      row.updated_at instanceof Date ? row.updated_at.toISOString() : String(row.updated_at ?? ''),
  };
}

export function mapSiteSettings(row: Record<string, unknown>): SiteSettings {
  return {
    id: row.id as string,
    agentNameEn: row.agent_name_en as string,
    agentNameUr: row.agent_name_ur as string | null,
    taglineEn: row.tagline_en as string | null,
    taglineUr: row.tagline_ur as string | null,
    phone: row.phone as string,
    whatsapp: row.whatsapp as string,
    email: row.email as string | null,
    officeAddress: row.office_address_en as string | null,
    officeAddressUr: row.office_address_ur as string | null,
    facebookUrl: row.facebook_url as string | null,
    instagramUrl: row.instagram_url as string | null,
    youtubeUrl: row.youtube_url as string | null,
    yearsExperience: Number(row.years_experience ?? 0),
    dealsClosed: Number(row.deals_closed ?? 0),
    happyClients: Number(row.happy_clients ?? 0),
    agentPhoto: row.agent_photo as string | null,
    agentBioEn: row.agent_bio_en as string | null,
    agentBioUr: row.agent_bio_ur as string | null,
  };
}
