import type { Property } from './types';

export function mapProperty(row: Record<string, unknown>): Property {
  return {
    id:             row.id as string,
    propertyId:     row.property_id as string,
    slug:           row.slug as string,
    title:          row.title as string,
    titleUr:        row.title_ur as string | null,
    description:    row.description as string | null,
    descriptionUr:  row.description_ur as string | null,
    purpose:        row.purpose as Property['purpose'],
    category:       row.category as Property['category'],
    subCategory:    row.sub_category as string | null,
    status:         (row.status as Property['status']) ?? 'AVAILABLE',
    priceType:      (row.price_type as Property['priceType']) ?? 'FIXED',
    price:          row.price != null ? Number(row.price) : null,
    rentPrice:      row.rent_price != null ? Number(row.rent_price) : null,
    size:           Number(row.size),
    sizeUnit:       (row.size_unit as Property['sizeUnit']) ?? 'MARLA',
    bedrooms:       row.bedrooms != null ? Number(row.bedrooms) : null,
    bathrooms:      row.bathrooms != null ? Number(row.bathrooms) : null,
    floors:         row.floors != null ? Number(row.floors) : null,
    facing:         row.facing as string | null,
    city:           (row.city as string) ?? 'Lahore',
    society:        row.society as string | null,
    area:           row.area as string | null,
    address:        row.address as string | null,
    mapLat:         row.map_lat as number | null,
    mapLng:         row.map_lng as number | null,
    photos:         (row.photos as string[]) ?? [],
    isCorner:       Boolean(row.is_corner),
    isParkFacing:   Boolean(row.is_park_facing),
    isGated:        Boolean(row.is_gated),
    hasSecurity:    Boolean(row.has_security),
    hasGas:         Boolean(row.has_gas),
    hasElectricity: Boolean(row.has_electricity),
    hasWater:       Boolean(row.has_water),
    hasGarage:      Boolean(row.has_garage),
    hasGarden:      Boolean(row.has_garden),
    hasServantQtr:  Boolean(row.has_servant_qtr),
    possession:     (row.possession as Property['possession']) ?? 'AVAILABLE',
    featured:       Boolean(row.featured),
    isActive:       Boolean(row.is_active),
    views:          Number(row.views ?? 0),
    createdAt:      row.created_at as string,
    updatedAt:      row.updated_at as string,
  };
}
